### ISSUE TITLE
I need to contact with you

### ISSUE THREAD

**Issue by quexpl** [cpjk/dotfiles#1]
Hi @cpjk I'm trying to reach you regarding the canary project. https://github.com/cpjk/canary/pull/83 
If it's still an offer I would like to be a maintainer of canary.

**Comment by cpjk** [comment]
Hey @quexpl, i'm sorry for the late response! Non-work github notifications have been getting lost in the deluge of work-related   notifications.

> If it's still an offer I would like to be a maintainer of canary.

Awesome! I've sent you a collaborator invite! Thank you! It's been a while since i've written elixir, but if you need PR reviews, I'm happy to step in!

**Comment by quexpl** [comment]
Thanks @cpjk, sure additional pair of eyes would be great for reviews!
I will try to work on canary next week. But there is another thing - would it be also possible to have access to the hex.pm. I think that after updating deps we might to publish a new release, what do you think?

Thank you! :)

**Comment by cpjk** [comment]
Cool! It looks like I should be able to add you as an owner of the package on hex. Would you mind pinging me at cpjkelly@gmail.com from the email you will use for hex, and i can add you as an owner using that email?

**Comment by cpjk** [comment]
Cool! It looks like I can add you as an owner. I think I need your email though. I messaged you on keybase. Would you mind sending me your email there, so neither of our emails are indexed my bots? Thanks!
